### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by lutzky** [lutzky/ttime3#29]
https://developers.google.com/analytics/devguides/collection/analyticsjs/

Interesting analytics:

* How often people perform actions
* How long schedule generation actually takes for people

**Comment by chaosite** [comment]
Please don't. You don't really need it and the site is fun and fast without it.

I already block the stuff you added on issue #9...

**Comment by lutzky** [comment]
Fair enough; if I add this, it should be opt-in (off by default).
