### ISSUE TITLE
Advanced course search

### ISSUE THREAD

**Issue by chaosite** [lutzky/ttime3#35]
It would be nice to be able to search for courses using parameters other than name or course number.

Examples:

1. **Exam date range**. (This one is important)
2. Faculty (even though you kinda get it for free with the way the course numbers are structured and sorting).
3. Teacher name

Sufficiently advanced course search (i.e., indistinguishable from magic) would be able to suggest courses that can be fitted into the current schedule, taking into consideration both lecture times and exam times.

Checklist added from later comment so it appears as a progress bar for the issue:

* [x] Add the "minimal test date distance" setting to settings. I think a default value of 3 is reasonable.
* [x] The "add course" dropdown will always color any courses that don't "fit" (in the sense described above) in red.
* [x] There will be a checkbox directly under the dropdown titled "Only show courses which fit test schedule". This will hide courses that would've been shown in red.
* [x] Have a button at the top of the "Selected Schedules" lists to popup a test schedule. This test schedule will highlight any tests which are too close to any of the other ones.

**Comment by chaosite** [comment]
Yes, sure. My one comment is that doing it like this will make it not very discoverable. The important thing it will solve is searching for "Keren Censor's Seminar" which is actually title "Computer Science Seminar 5" or something.

I do think that 1 is interesting enough to get its own UI if needed, though. It really is a common enough use-case of choosing courses by what fits in your exam schedule.

**Comment by lutzky** [comment]
Alright, so search by exam date range. Can you describe this in terms of user stories?

**Comment by chaosite** [comment]
The epic is "As a student who already chose N courses, I want to find an N+1 course that has an exam in the gap in my exam schedule."

So now there's the question of how to implement it. You can add this to the course search feature, or you can add a new feature that suggests new courses based on your existing course list.

**Comment by chaosite** [comment]
Agreed on the definition, we don't actually care about the actual gaps, the important bit is "K days of separation from dates already in the list". Making the annoying issue of figuring out the test period (and occasionally there are tests outside the scheduled test periods!) irrelevant is definitely a good idea.

Thinking about this some more, there is also the issue of moed A vs moed B - i.e., is it legal if only one of the moeds is legal. Maybe you need another tweakable in settings.

Other than that, SGTM! :+1:
