### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by chaosite** [lutzky/ttime3#37]
Errors from the JavaScript console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://storage.googleapis.com/repy-176217.appspot.com/latest.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://storage.googleapis.com/repy-176217.appspot.com/latest.json. (Reason: CORS request did not succeed).[Learn More]
Failed to load catalog: Error: "Network Error"

    onerror https://lutzky.net/ttime3/dist/ttime.js:8
    dispatchEvent https://lutzky.net/ttime3/dist/ttime.js:8
    handleError https://lutzky.net/ttime3/dist/ttime.js:8 
    _ https://lutzky.net/ttime3/dist/ttime.js:8 
    emit https://lutzky.net/ttime3/dist/ttime.js:8 
    _onFinish https://lutzky.net/ttime3/dist/ttime.js:8
```

Browser is Firefox 65.0.1 on Linux.

**Comment by lutzky** [comment]
I haven't tested on Firefox at all, to be honest. I though I worked out the CORS headers correctly, I'll check again. Can you please confirm:

* Does this reproduce on Chrome for you?
* Does modifying the catalog to something other than "latest" (especially to the cheesefork ones) help?

**Comment by chaosite** [comment]
- Chrome 72.0.3626.121 on Mac loads correctly, Firefox 66.0b14 on Mac reproduces this issue. I'm rather not install Chrome on my Linux machine right now.
- No, it doesn't matter what I select, they all fail.

**Comment by lutzky** [comment]
Well, that should work around the issue, at any rate. @chaosite, can you please confirm? (The issue reproduced on Firefox for me before the fix and doesn't reproduce afterwards).
Apparently something is wrong with using the xmlhttprequest-ts library, this may or may not be similar to https://github.com/ReactiveX/rxjs/issues/4455.

**Comment by chaosite** [comment]
Yeah, it works for me now. Thanks!
