### ISSUE TITLE
Support "recommended catalog"

### ISSUE THREAD

**Issue by lutzky** [lutzky/ttime3#42]
Currently, we have the following banner:

> **Data may be stale.** As of 2019-07-03, the Technion have not updated the REPY file. We recommend you go to the Settings tab and, under Catalog URL→Presets, choose "Winter 2019/20 (CheeseFork)".

It *always* shows up. What I'd really like is for ttime3 to define a "blessed" catalog URL, and show the popup if you're *not* using it. Also, the popup should allow you to *immediately set* the blessed catalog. So it should look like this:

> **Using old catalog.** For up-to-date results, **[click here to use *Winter 2019/20 (CheeseFork)*]**.

**Comment by lutzky** [comment]
@chaosite wdyt?

**Comment by chaosite** [comment]
Yeah, SGTM. It's slightly annoying that it's manual, though.

**Comment by lutzky** [comment]
Yeah, but I'm not sure there's a good alternative. Currently, all users have the current catalog specified as `catalogUrl` in the settings, with no way of telling if that's actually their preference or just happened to be the default at the time. That being said, the default has always been the same so far:

https://github.com/lutzky/ttime3/blob/ebac603f900b469391d4b80bec549e4ec13288aa/src/main.ts#L32-L33

BTW, to mess with your current setting you can do this in the JS console:

```javascript
settings = JSON.parse(localStorage.ttime3_settings);
console.info(settings.catalogUrl);
settings.catalogUrl = 'some other URL';
localStorage.ttime3_settings = JSON.stringify(settings);
```

So the major obstacle here is upgrade path - if we assume everyone using `latest.json` just has it set to that by default, we would mess up the settings for people who have chosen it manually. Ideas?

**Comment by chaosite** [comment]
One of the things that are nice about the domain is that it's inherently time based.

Add a date to the local-storage, and have a date associated with the "blessed" profile. Only suggest switching to blessed if the user's setting is older. Assume no setting is old.

This will also fix rolling over in the next semester.

**Comment by lutzky** [comment]
Hmm, I think I like it! A couple of questions though:

1. What are the appropriate rollover dates? Presumably, students are interested in starting looking at the next semester before it starts. I'd love to go with "if a file has been *created* after the user last chose a catalog, recommend switching to it. Unfortunately, I can't seem to get the creation date (or last-modified date) of files from the github API.
2. Do we indeed auto-rollover, and just show a notice at the top? That might be disruptive :man_shrugging:

**Comment by lutzky** [comment]
So 1 is possible, using the commit API:

```shell
$ curl -s 'https://api.github.com/repos/michael-maltsev/cheese-fork/commits?sha=gh-pages&path=courses/courses_201901.js' \
  | jq -r '.[0].commit.committer.date'
2019-07-05T06:29:29Z
```

So does this strategy make sense? "If newest cheesefork file has its latest commit later than when the user last changed catalogs (and if we don't know when the user last changed catalogs, it's negative-infinity), then force-change to the latest cheesefork catalog"

**Comment by chaosite** [comment]
That won't work, the latest file gets daily commits, so that would just be annoying and keep overriding changes. We want to change over if the latest file is of a different semester than the previously seen file.

1. I thought you were talking about manually blessing a preset.
1. Single click apply would also work. But I think that for the interesting case (user hasn't been to the site since making the timetable last semester...)

**Comment by lutzky** [comment]
I don't want to manually bless a new preset each time a cheesefork schedule comes out. Here's a simpler possible solution:

1. Make the new initial value for `catalogUrl` be `""`.
2. A `catalogUrl` value of `""` would mean "use latest Cheesefork catalog"
3. Whenever `catalogUrl` is non-empty, we will show a notification on the top (replacing the current one) saying "You are currently using catalog *[human-readable-catalog-name]*, [click here](#) to use the default." Clicking it would empty `catalogUrl` and reload.

WDYT?
