### ISSUE TITLE
Showing wrong dates for exams

### ISSUE THREAD

**Issue by chaosite** [lutzky/ttime3#44]
Checkout 236363 for an example.

The data in the CheeseFork JSON is:

 ```"מועד א":"בתאריך 02.02.2020 יום א","מועד ב":"בתאריך 02.03.2020 יום ב"```

But the in the UI, the date for Moed A is displayed as "2020-03-01".

**Comment by chaosite** [comment]
See #45.

**Comment by lutzky** [comment]
The problem here isn't with the CheeseFork parser, it's with the rendering.

**Comment by lutzky** [comment]
https://github.com/lutzky/ttime3/commit/3f6520d3f81c1f511d4ef09dd081c0f932f111c0 should help, but we're still showing off-by-one dates in the Test Schedule on the main tab (test dates in the Catalog tab have been corrected).
