### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by chaosite** [lutzky/ttime3#47]
Some minor UI/UX enhancements that I think may go a long way:

- [x] If a user clicked forbid on a course, nothing happens until "generate schedules" is pressed. Something should happen, like a toast that says "You've made changes, click here to generate courses" or the generate courses button should change colors or start animating.
- [ ] The generate schedules button and the editable course list should be above the course info, having them below requires too much scrolling when working.
- [x] The list of forbidden classes (and the option to unforbid them) should be in the schedule tab, not in settings.
- [x] Courses in the course list should have 2 buttons, "no lectures" and "no tutorials", that when pressed forbid/unforbid all lectures or tutorials for that course, since that's a common decision. The buttons will also show the current state using colors or icons.
- [ ] I think the list version of the schedule can be moved to the left column, below the timetable version. The controls (including sorting) should stay on the right.

**Comment by lutzky** [comment]
> Some minor UI/UX enhancements that I think may go a long way:
> 
> * [ ]  If a user clicked forbid on a course, nothing happens until "generate schedules" is pressed. Something should happen, like a toast that says "You've made changes, click here to generate courses" or the generate courses button should change colors or start animating.

Opened #51.

> * [ ]  The generate schedules button and the editable course list should be above the course info, having them below requires too much scrolling when working.

I think it works better this way. The top of the page is intended for navigating different schedules (schedule-view on the left, details-view on the right), and the bottom of the page is intended for editing and rescheduling. I could make the thing its own tab... but it would still be split that way. "Schedules" tab would have schedule-view, next/prev, sort-buttons and schedule-details; "Select courses" tab would have add/remove courses, test schedule, and the "generate schedules" button. I'm not sure that's better.

I think moving the list version of the schedule to the left column alleviates a lot of this.

> * [ ]  The list of forbidden classes (and the option to unforbid them) should be in the schedule tab, not in settings.

That's a regression, opened #49.

> * [ ]  Courses in the course list should have 2 buttons, "no lectures" and "no tutorials", that when pressed forbid/unforbid all lectures or tutorials for that course, since that's a common decision. The buttons will also show the current state using colors or icons.

Interesting feature request, opened #50.

> * [ ]  I think the list version of the schedule can be moved to the left column, below the timetable version. The controls (including sorting) should stay on the right.

This only works easily if the whole thing moves to the bottom, but I think it looks good! WDYT?

![image](https://user-images.githubusercontent.com/8140/61406680-3ce9d000-a8d4-11e9-9c1f-14e35d869818.png)

**Comment by chaosite** [comment]
> I think moving the list version of the schedule to the left column alleviates a lot of this.

SGTM. The main issue was that clicking the generate schedules button required a whole bunch of scrolling (also, I knew it was there).


> This only works easily if the whole thing moves to the bottom, but I think it looks good! WDYT?

Yeah, it looks great!
Maybe center-justify the controls on the left?

**Comment by lutzky** [comment]
OK, pushed. I center-justified *some* of the controls; centering stuff in CSS (even/especially with bootstrap) is surprisingly hard.

I believe this finishes all the items from this issue, either fixed directly or opened a separate issue for.
