### ISSUE TITLE
"Forbid" link on Schedules tab doesn't turn into "Unforbid"

### ISSUE THREAD

**Issue by lutzky** [lutzky/ttime3#49]
When clicking "Forbid" on a group, it should turn into "Unforbid" (also it should be "Unforbid" if the group was already forbidden). This worked before, it's a regression.

**Comment by chaosite** [comment]
Maybe I'm not understanding this?

How can I unforbid a group from the schedules tab after forbidding it and generating new schedules, if it never shows up?

**Comment by lutzky** [comment]
Ah, OK, you meant the small :no_entry_sign: in the rendered schedule. There's another button - click the :information_source: button next to a course in "Selected Courses", there you can (un)forbid any group.

I'm not sure how to improve this; maybe the selected courses list can have a small hint, e.g. light-grey " :arrow_left: some groups hidden" after the :information_source: ?

**Comment by chaosite** [comment]
Ah. Well, I didn't know that, and I wouldn't have thought to click on an ℹ️ to find additional controls. A hint would definitely be useful.

**Comment by lutzky** [comment]
Actually, it might be easier to move the Forbidden Groups list from Settings to be under the test schedule (there's plenty of room there now), and that can also be a good place for a hint about how to forbid groups in the first place. WDYT?

**Comment by chaosite** [comment]
SGTM!

**Comment by chaosite** [comment]
Yes, this is very fixed now!
