### ISSUE TITLE
Fast {un,}forbid for all lectures/tutorials

### ISSUE THREAD

**Issue by lutzky** [lutzky/ttime3#50]
From @chaosite:

> Courses in the course list should have 2 buttons, "no lectures" and "no tutorials", that when pressed forbid/unforbid all lectures or tutorials for that course, since that's a common decision. The buttons will also show the current state using colors or icons.

**Comment by lutzky** [comment]
@chaosite, what do you have in mind for the UI for this? See strawman in screenshot: (first [user-slash](https://fontawesome.com/icons/user-slash?style=solid) would be "no lectures", second one would be "no tutorials").

![image](https://user-images.githubusercontent.com/8140/61590959-defd0700-abb7-11e9-96b9-4f7fc7812c08.png)

**Comment by chaosite** [comment]
Icons seem unrelated (person with seatbelt?)

Maybe have "L" and "T", clicking them (or manually forbidding) puts a crossed out circle over them?

**Comment by chaosite** [comment]
Also obviously tool-tips will be important here.

**Comment by lutzky** [comment]
A couple of problems:

* I can't seem to get a nice "L with a crossed out circle symbol" simply, and I don't want to be in the business of making my own SVGs here
* There are three valid states here (all/some/none), so one would need a tri-state checkbox (which bootstrap supports) - however, that would need a letter/abbreviation next to it, and that's a tight fit with long course names ("חשבון דיפרנציאלי ואינטגרלי 2ת'")

Maybe something in the drop-down?
