### ISSUE TITLE
Clicking forbid from schedule does not trigger "generate schedules" toast

### ISSUE THREAD

**Issue by chaosite** [lutzky/ttime3#52]
As the title says, if you click the "🚫" symbol that is on each colored block in the schedule, the toast is not triggered. It probably should be.

**Comment by chaosite** [comment]
Actually I'm mistaken, the behavior is that only the first forbid event triggers the toast.

I'm not clear on the logic for triggering the toast, but this does not seem like a bug anymore. Closing.

**Comment by lutzky** [comment]
That's definitely intended, but I'm open to suggestions.
